import { Poppins, Inconsolata, Asap, Maven_Pro } from "next/font/google";
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

// Poppins (Todos os pesos)
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// Inconsolata (Regular)
const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inconsolata",
});

// Asap (Bold)
const asap = Asap({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-asap",
});

// Maven Pro (Regular)
const mavenPro = Maven_Pro({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-maven",
});

export const metadata: Metadata = {
  title: "Erick Marques",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inconsolata.variable} ${asap.variable} ${mavenPro.variable} antialiased`}>

        <section id="hero" className="max-w-full">
          <Image
            src="/hero.svg"
            alt="Next.js logo"
            quality={100}
            width={128}
            height={128}
            className="h-auto w-screen object-cover absolute top-0 left-0 z-[-1]"
            priority
          />
        </section>

        <section className="max-w-screen-xl mx-auto px-4 flex flex-col gap-6">
          <Header/>

          {children}    

          <Footer.Root>
            <Footer.Header />
            <Footer.Body/>
            <Footer.Botom/>
          </Footer.Root>
        </section>
      </body>
    </html>
  );
}
