import { Poppins, Inconsolata, Asap, Maven_Pro } from "next/font/google";
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";


// Poppins (Todos os pesos)
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// Inconsolata (Regular)
const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inconsolata",
});

// Asap (Bold)
const asap = Asap({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-asap",
});

// Maven Pro (Regular)
const mavenPro = Maven_Pro({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-maven",
});

export const metadata: Metadata = {
  title: "Erick Marques",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inconsolata.variable} ${asap.variable} ${mavenPro.variable} antialiased`}>
      
        <section id="hero" className="max-w-full">
          <Image
            src="/hero.svg"
            alt="Next.js logo"
            quality={100}
            width={128}
            height={128}
            className="h-auto w-screen object-cover absolute top-0 left-0 z-[-1]"
            priority
          />
        </section>

        <section className="max-w-screen-xl mx-auto px-4">
          <header className="flex justify-between items-center pt-2">
            <ul className="md:flex gap-2 hidden">
              <li>Início</li>
              <li>Início</li>
              <li>Início</li>
            </ul>
            <Image
              src="/logo.svg"
              alt="Next.js logo"
              width={80}
              height={80}
              className="h-auto w-20"
              priority
            />
            <button className="bg-[#4B2DBB] text-white px-4 py-1 rounded-lg">
              Work Flow
            </button>
          </header>

          {children}
        </section>
      </body>
    </html>
  );
}
