import { Poppins, Inconsolata, Asap, Maven_Pro } from "next/font/google";
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css";


// Poppins (Todos os pesos)
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// Inconsolata (Regular)
const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inconsolata",
});

// Asap (Bold)
const asap = Asap({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-asap",
});

// Maven Pro (Regular)
const mavenPro = Maven_Pro({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-maven",
});

export const metadata: Metadata = {
  title: "Erick Marques",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inconsolata.variable} ${asap.variable} ${mavenPro.variable} antialiased`}>

        <section id="hero" className="max-w-full">
          <Image
            src="/hero.svg"
            alt="Next.js logo"
            quality={100}
            width={128}
            height={128}
            className="h-auto w-screen object-cover absolute top-0 left-0 z-[-1]"
            priority
          />
        </section>

        <section className="max-w-screen-xl mx-auto px-4">
          <header className="flex justify-between items-center pt-2">
            <ul className="md:flex gap-2 hidden">
              <li>Início</li>
              <li>Início</li>
              <li>Início</li>
            </ul>
            <Image
              src="/logo.svg"
              alt="Next.js logo"
              width={80}
              height={80}
              className="h-auto w-20"
              priority
            />
            <button className="bg-[#4B2DBB] text-white px-4 py-1 rounded-lg">
              Work Flow
            </button>
          </header>

          {children}
          <footer>
            <section className="py-20 border-t border-0.5 border-gray-500">
              <h1> Erick Marques</h1>
              <strong>erickmarques3@gmail.com</strong>
            </section>
            <section className="flex justify-between items-center border-t border-0.5 border-gray-500">
              <div className="">
                <h1>Entre em contato</h1>
                <h1 className="text-[#FF5B50] font-bold">Direto por WhatisApp para suporte</h1>
                <div className="bg-[#5A5757] w-96 justify-between flex items-center pl-5 rounded-sm">
                  <strong>+55 21 976818468</strong>
                  <button className="text-black p-5 bg-white">Iniciar converça</button>
                </div>
              </div>
              <div className="flex border-l border-0.5 border-gray-500 pl-80 gap-30 py-4">
                <div>
                  <h1 className="text-gray-600">Empresa</h1>
                  <ul className="flex flex-col gap-2">
                    <li>RocketSeat</li>
                    <li>Universidade Estacio</li>
                    <li>UX Unicórnio</li>
                    <li>UI Start</li>
                    <li>Six Creative</li>
                    <li>Incentive.me</li>
                    <li>Satel Brasil</li>
                    <li>Empy</li>
                  </ul>
                </div>
                <div>
                  <h1 className="text-gray-600">Links</h1>
                  <ul className="flex flex-col gap-2">
                    <li>www.rocketseat.com.br</li>
                    <li>Universidade Estacio</li>
                    <li>www.uxunicornio.vip</li>
                    <li>www.uiexpert.com.br</li>
                    <li>www.sixcreative.com.br</li>
                    <li>www.incentive.me</li>
                    <li>www.satel-sa.com.br</li>
                    <li>www.empy.com.br</li>
                  </ul>
                </div>
              </div>
            </section>
            <section className="py-20 border-t border-0.5 border-gray-500">
              <h1>www.erickmarques.app.com</h1>

            </section>
          </footer>
        </section>
      </body>
    </html>
  );
}
